//什么是滤波器

//https://zh.wikipedia.org/wiki/%E6%BF%BE%E6%B3%A2%E5%99%A8

//滤波器的用途实例

//https://www.armadamusic.com/university/music-production-articles/eq-explained-the-basics#:~:text=Equalization%20%E2%80%93%20or%20EQ%20%E2%80%93%20is%20one,entire%20songs%20%E2%80%93%20of%20its%20imperfections.


//HPF



//LPF




// band pass filter
//BPF
// Q factor : https://zh.wikipedia.org/wiki/%E5%93%81%E8%B3%AA%E5%9B%A0%E5%AD%90
// damping : https://zh.wikipedia.org/wiki/%E9%98%BB%E5%B0%BC
